SYNTHETIC_USER_PROFILES = [
    {
        "id": "simple_homework_001",
        "level": "simple",
        "goal": "start homework",
        "identity": ["student"],
        "interests": ["gaming"],
        "friction": ["task_initiation"],
        "telemetry": {
            "momentum": 0.35,
            "overwhelm": 0.45,
            "inactivity_minutes": 25,
            "retry_count": 1,
        },
    },
    {
        "id": "simple_spanish_001",
        "level": "simple",
        "goal": "study Spanish",
        "identity": ["student"],
        "interests": ["coding"],
        "friction": ["boredom", "unclear_entry"],
        "telemetry": {
            "momentum": 0.5,
            "overwhelm": 0.25,
            "voice_usage": True,
        },
    },
    {
        "id": "medium_podcast_001",
        "level": "medium",
        "goal": "launch podcast",
        "identity": ["creator"],
        "interests": ["film", "cameras"],
        "friction": ["perfectionism", "too_many_steps"],
        "telemetry": {
            "momentum": 0.55,
            "overwhelm": 0.5,
            "rapid_exits": True,
        },
    },
    {
        "id": "medium_relationship_001",
        "level": "medium",
        "goal": "understand girlfriend's gaming hobby",
        "identity": ["relationship_bridge"],
        "interests": ["cameras", "film"],
        "friction": ["identity_mismatch", "community_intimidation"],
        "telemetry": {
            "momentum": 0.6,
            "overwhelm": 0.2,
        },
    },
    {
        "id": "advanced_burnout_engineer_001",
        "level": "advanced",
        "goal": "finish a complex software project while burned out",
        "identity": ["expert", "software_engineer"],
        "interests": ["systems", "automation"],
        "friction": ["burnout", "avoidance", "scope_creep"],
        "telemetry": {
            "momentum": 0.3,
            "overwhelm": 0.75,
            "fatigue_score": 0.85,
            "inactivity_minutes": 90,
        },
    },
    {
        "id": "advanced_founder_001",
        "level": "advanced",
        "goal": "ship a startup MVP",
        "identity": ["founder_creator"],
        "interests": ["investing", "coding"],
        "friction": ["ambiguous_priorities", "pressure", "overwhelm"],
        "telemetry": {
            "momentum": 0.65,
            "overwhelm": 0.6,
            "high_completion": True,
        },
    },
    {
        "id": "edge_perfectionism_001",
        "level": "edge",
        "goal": "finish a paper despite perfectionism paralysis",
        "identity": ["student", "high_capability"],
        "interests": ["film", "psychology"],
        "friction": ["perfectionism", "emotional_block", "low_confidence"],
        "telemetry": {
            "momentum": 0.45,
            "overwhelm": 0.8,
            "retry_count": 8,
        },
    },
    {
        "id": "edge_identity_mismatch_001",
        "level": "edge",
        "goal": "join a new professional community without feeling fake",
        "identity": ["community_entry"],
        "interests": ["watches", "entrepreneurship"],
        "friction": ["identity_mismatch", "community_intimidation"],
        "telemetry": {
            "momentum": 0.5,
            "overwhelm": 0.55,
        },
    },
]
